version: '3.5'

services:
  frontend:
    build: 
      context: ./frontend
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
  backend:
    build:
      context: ./backend
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./backend:/go/src/github.com/estensen/runtime-systems/backend
    ports:
      - 8080:8080
